questions = {
    "Memory bandwidth": "",
    "VLIW": "",
    "Score-boarding": "",
    "Shared-memory architecture": "",
    "Amdahl's law": "",
    "Virtual memory miss": "",
    "Bus snooping": "",
    "Cache coherence": "",
    "Out-of-order execution": "",
    "Inexact exception": "",
    "Memory architecture: accumulator": "",
    "Memory architecture: Memory-memory": "",
    "Memory architecture: Stack": "",
    "Memory architecture: Load-store": "",
    "CPU Performance Equation (explain terms)": "",
    "Execution time (calculate)": "",
    "MIPS (calculate)": "",
    "MFLOPS": "",
    "Name dependencies (name two kinds)": "",
    "True dependencies": "",
    "Hazards": "",
    "5 Classic pipeline stages": "",
    "CPI": "",
    "dominance": "",
    "basic block": "",
    "inverted page table": "",
    "true sharing misses": "",
    "register renaming": "",
    "data dependency": "",
    "way prediction": "",
    "unified cache": "",
    "sequential consistency": "",
    "general purpose register instruction set architecture": "",
    "memory hierarchy": "",
    "MIMD": "",
    "SIMD": "",
    "make the common case fast": "",
    "locality of reference": "",
    "The SPEC benchmark series": "",
    "Control dependency": "",
    "Reorder buffer": "",
    "False sharing": "",
    "imprecise exceptions": "",
    "Five levels of parallelism (used to increase computer system performance)": "",
    "TLB": "Translation look-aside buffer, a cache used by memory management hardware to improve virtual address translation speed",
    "Virtual address": "The address space available to a process. The virtual addresses are separate from physical addresses and are mapped by the OS. This provides process isolation. Several processes sharing the same physical memory. Relocation."
}
